[phases.build]
cmds = [
    "pip install -r requirements.txt"
]

[phases.install]
cmds = ["echo 'Dependencies installed'"]

[start]
cmd = "python3 -m gunicorn jossie_fancies.wsgi --bind 0.0.0.0:$PORT"