services:
  - type: web
    name: jossiefancies
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jossie_fancies.wsgi:application"
    postDeployCommand: "python manage.py create_default_superuser && python manage.py check_cloudinary_config"
    plan: free
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "jossiefancies.onrender.com,.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        value: "your-secret-key-here"
      - key: DATABASE_URL
        fromDatabase:
          name: jossiefancies-db
          property: connectionString

databases:
  - name: jossiefancies-db
    plan: free
